---
- hosts: dev
  become: True
  tasks:
    - name: Start the container
      docker_container:
        name: helloscript
        image: "orlym/hello_world:{{DOCKER_TAG}}"
        state: started
        volumes:
          - /data/test/
