---
- hosts: dev
  become: True
  tasks:
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present       
    - name: Start the container
      docker_container:
        name: helloscript
        image: "orlym/hello_world:49"
        command: chmod +x hello_world.sh
        state: started
        volumes:
            - "/data/test/:/data/test/"
        
